project:
  type: website

website:
  title: "l1rotation"
  navbar:
     left:
      - href: index.qmd
        text: Home
      - text: "Articles"
        menu:
          - text: "Getting Started"
            href: vignettes/documentation.qmd
          - text: "Intuition"
            href: intuition.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



